application: {{ appname }}
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /fonts
  static_dir: fonts

- url: /locales
  static_dir: locales

- url: /partials
  static_dir: partials

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: noat.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

env_variables:
  APP_KEY: '{{ appkey }}'